Fix an error when running the gem binary standlone
When running the manageiq-cross_repo binary from the installed gem
bundler isn't automatically required which leads to:

`'block in with_test_env': undefined method `with_clean_env' for Bundler:Module (NoMethodError)`